server:
  port: 8081
spring:
  application:
    name: eurekaserver
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/