server:
  port: 0
spring:
  application:
    name: userservice
  datasource:
    #    url: jdbc:postgresql://localhost:5432/your_database_name
    url: jdbc:postgresql://localhost:5432/user_db
    #    username: your_username
    username: postgres
    #    password: your_password
    password: fadeevaaa
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/